criterion: gini
splitter: best
max_depth: null
min_samples_split: 2
min_samples_leaf: 1
min_weight_fraction_leaf: 0.0
max_features: null
random_state: 42
max_leaf_nodes: null
min_impurity_decrease: 0.0
class_weight: balanced
ccp_alpha: 0.0